### ISSUE TITLE
UIImage extension clips image

### ISSUE THREAD

**Issue by agquick** [thii/FontAwesome.swift#46] opened 2015-09-30 21:16 UTC
When you use the UIImage extension to draw an image from a font icon, it clips the image for all the icons that are wider than tall. I think the bug is here:

https://github.com/thii/FontAwesome.swift/blob/master/FontAwesome/FontAwesome.swift#L81

The `max` call should instead be a `min` when determining the font size.

For example the icon `fa-newspaper-o` when used with a font size of 30px actually generates an image that is 34px wide.

**Comment by oliverdowling** [comment] 2015-10-06 23:44
I have noticed this behaviour as well, but I don't think that line is the cause of this issue. If you set the size as a square, the sides are still cut off, so `min`/`max` makes no difference in that case. I think it should still be `min` though, because it should be an icon that fits inside the given size. if you give a size of 100x10, you would still want to see the whole icon, and it should be size 10, shouldn't it? I don't believe that's the same issue though...

**Comment by agquick** [comment] 2015-10-07 00:01
Yup you're right. The way I get around that right now is looking up the ratio of the icon on fontawesome.io and setting the size of the image accordingly (i.e. if the icon isn't a square don't set the image to one). But this only works by changing max to min.

**Comment by oliverdowling** [comment] 2015-10-07 00:12
On FontAwesome.io in their fixed width example, they have the width set as `1.28571429em` which I assume is the maximum width:height ratio for their icons. When I get a chance in a few hours, I'll add this magic number into a pull request, along with your min/max fix.

**Comment by thii** [comment] 2015-10-07 12:58
Fixed in #47.

**Closed by thii** 2015-10-07 12:58 UTC
