### ISSUE TITLE
FontAwesomeTabBarItem.swift:58:24: Use of undeclared type 'ImageConfig'

### ISSUE THREAD

**Issue by schystz** [thii/FontAwesome.swift#150] opened 2017-07-19 11:48 UTC
Hi guys, first I want to thank you for bringing FontAwesome to iOS! You guys are really awesome! I have been using the library on a project which is written in Swift 2 and I've been very happy so far. I recently migrated to Swift 2.3 and it worked out fine. But now I am working on migrating it to Swift 3 and started getting a problem with FontAwesome. Upon building, I got two errors immediately from Xcode:

```
ProjectPath/Pods/FontAwesome.swift/FontAwesome/FontAwesomeImageView.swift:54:24: Use of undeclared type 'ImageConfig'
ProjectPath/Pods/FontAwesome.swift/FontAwesome/FontAwesomeTabBarItem.swift:58:24: Use of undeclared type 'ImageConfig'
```

I tried everything from cleaning my project's derived data + clean + build, cleaning cocoapod cache, removing and re-installing the pods - but to no avail. I also tried to use it on a completely new Swift 3 project and I am getting the same build error. I'm trying to google similar issues but I am unable to find similar cases to mine. I hope someone from the contributors or from the community can help me. Note that I am running on El Capitan 10.11.6 and Xcode 8.2.1, and I am using the latest version of FontAwesome.swift which is at 1.2.0

**Comment by thii** [comment] 2017-07-19 13:07
@schystz Hi, thanks for reporting the issue. I really appreciate it. 

Looks like you are using an outdated version of Xcode. Could you please update your Xcode and try again? If the problem still persists, please make a sample project which reproduces the problem, I will try to investigate into it.

**Comment by schystz** [comment] 2017-07-19 13:53
Thank you for the quick reply @thii !

The latest version of Xcode I can install on El Capitan is Xcode 8.2.1, thus I am stuck with it until I have migrated the project to Swift 3 and make sure it works. Until then I can only update my OS and install higher version of Xcode :(

Please see below project I quickly created to demonstrate the issue - https://github.com/schystz/FontAwesomeProject

**Comment by thii** [comment] 2017-07-19 17:11
I could build your project successfully without any issue on Xcode 8.3.3, so the problem is probably with Xcode 8.2.1. There are workarounds to install Xcode 8.3 on El Capitan (like [this](https://github.com/michalzelinka/Xcode83onElCapitan)) so might want to consider those. You might not be able to submit your app to the App Store with the modified Xcode but you can always use CI services for those tasks.

I'm closing this since the issue is out of the scope of this project.

**Closed by thii** 2017-07-19 17:11 UTC

**Comment by schystz** [comment] 2017-07-20 00:26
Phew, I got it working by downgrading to FontAwesome 1.1.0
